recipes:
  train_clients_deaths_rescoring_model:
    input:
      dataset: clients_x_deaths
      chunked: False 
      select:
        query:
          constant_score: 
            filter:
              exists:
                field:
                  validation_done

    steps:
      - build_model:
          model:
            name: clients_deaths_ml
            method: RandomForestRegressor
            parameters:
              n_estimators: 20
              max_depth: 4
              min_samples_leaf: 5
            tries: 3
            test_size: 0.33
          numerical: .*(hit_score_.*|population|surface|matchid_hit_distance)$
          #categorical: .*(matchid_location_countrycode)$
          target: validation_decision
 