name: Build data

on: [push]

jobs:
  build:
    name: Docker image build CI
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Config
        run: make config
      - name: Recipe run
        run: make recipe-run watch-run
